### ISSUE TITLE
HTTP/500 when publishing a workbook

### ISSUE THREAD

**Issue by adbertram** [glenrobinson72/Tableau-Powershell-Scripts#1]
I've been trying to use your code to publish a workbook and it's not working. Can you confirm that this function works for you?

https://github.com/glenrobinson72/Tableau-Powershell-Scripts/blob/master/REST-API/Tableau-REST.psm1#L794

I've tried everything I can think of from using Invoke-RestMethod, double-checking my request, removing the connection credential and more. I can't seem to get a test workbook published.

**Comment by glenrobinson72** [comment]
Hi Adam,
Is this for a TWBX, or TWB?
Also what version of Tableau are you using?
Also, if you check the vizportal logs it should give you more information as to why it is failing? Can you let me know what it says?
Thanks
Glen

**Comment by adbertram** [comment]
It's for a TWBX but I tried a TWB as well. I think I'm using 9.2. I don't know much about Tableau itself; I was just put in charge of developing some automation around it. Here's my HTTP request:

```
POST http://tableau.qe.genomichealth.com/api/2.0/sites/2bc9d5f9-fdff-4715-98a6-0c4edb213961/workbooks HTTP/1.1
Content-Type: multipart/mixed; boundary=6691a87289ac461bab2c945741f136e6
ContentLength: 674886
X-Tableau-Auth: BN9HycpxW3pD7YkujbEyrYLTKrqz3mKm
User-Agent: Mozilla/5.0 (Windows NT; Windows NT 10.0; en-US) WindowsPowerShell/5.1.15063.502
Host: tableau.qe.domain.local
Content-Length: 674886

--6691a87289ac461bab2c945741f136e6
Content-Disposition: name="request_payload"
Content-Type: text/xml

<tsRequest>
  <workbook name="Sales-Forecast-Dashboard">
    <project id="a0774059-17b8-4423-8329-27e67503eae6"/>
  </workbook>
</tsRequest>
--6691a87289ac461bab2c945741f136e6
Content-Disposition: name="tableau_workbook"; filename="sfd.twbx"
Content-Type: application/octet-stream

<Lotsofworkbookcontenthere>

--6691a87289ac461bab2c945741f136e6--
```

Whenever I issue the request, nothing shows up in `C:\ProgramData\Tableau\Tableau Server\data\tabsvc\logs\vizportal\vizportal-0.log` however, I do see the HTTP/500 being returned in the httpd log.

```
10.3.241.50 - - 2017-08-16 08:43:34.216 Pacific Daylight Time 80 "POST /api/2.0/sites/2bc9d5f9-fdff-4715-98a6-0c4edb213961/workbooks?overwrite=False HTTP/1.1" "-" 500 216 "1453225" 1483013 WZRoJqwSeWwAAALMjbEAAAI7
```

**Comment by adbertram** [comment]
Would you mind giving me your actual HTTP request that works? I could then compare it to mine. I've been struggling with this for two days! I used Fiddler to capture the request.

**Comment by glenrobinson72** [comment]
So, this is the content of the request body for publishing the Regional.twbx file

--6691a87289ac461bab2c945741f136e6
Content-Disposition: name="request_payload"
Content-Type: text/xml

<tsRequest>
   <workbook name="test" showTabs="False">

     <project id="a7306682-18ac-11e7-b59b-178d311086e9" />
  </workbook>
</tsRequest>
--6691a87289ac461bab2c945741f136e6
Content-Disposition: name="tableau_workbook";filename="regional.twbx"
Content-Type: application/octet-stream

**<Actual Workbooks content>**
   
--6691a87289ac461bab2c945741f136e6--

Which looks to be pretty similar to what you have. 
I found that using Invoke-RestMethod didn't work with upload TWBX files (was fine for TWB), so which is why I use the System.Net.WebClient

I have never tried this on 9.x servers, only 10.x (I think) so cant vouch for it, but according to the documentation this should work.

My Vizportal.log looks like this
2017-08-16 18:46:03.933 +0100 (Default,glen,nPx7erfpTgaavW6pI3GYrw,WZSE2wqWI2oAAEVAIeYAAAE-) catalina-exec-30 : INFO  com.tableausoftware.domain.content.publishing.WorkbookPublishingService - Publishing workbook: test
2017-08-16 18:46:04.102 +0100 (Default,glen,nPx7erfpTgaavW6pI3GYrw,WZSE2wqWI2oAAEVAIeYAAAE-) catalina-exec-30 : INFO  com.tableausoftware.domain.content.publishing.WorkbookPublishingService - Uploading extract for workbook: test from twbPath C:\ProgramData\Tableau\Tableau Server\data\tabsvc\temp\regional.twbx5076707662949394723.tmp
2017-08-16 18:46:04.133 +0100 (Default,glen,nPx7erfpTgaavW6pI3GYrw,WZSE2wqWI2oAAEVAIeYAAAE-) catalina-exec-30 : INFO  com.tableausoftware.model.workgroup.service.VqlSessionService - Created session id:58668E61590B4E899C8234682E34FE68
2017-08-16 18:46:04.149 +0100 (Default,glen,nPx7erfpTgaavW6pI3GYrw,WZSE2wqWI2oAAEVAIeYAAAE-) catalina-exec-30 : INFO  com.tableausoftware.sos.TdfsProvider - inject extract/{73CC533E-EC44-4B06-9938-59194BA2E3CD}
2017-08-16 18:46:04.149 +0100 (Default,glen,nPx7erfpTgaavW6pI3GYrw,WZSE2wqWI2oAAEVAIeYAAAE-) catalina-exec-30 : INFO  com.tableausoftware.sos.Access.extract - inject folder C:\ProgramData\Tableau\Tableau Server\data\tabsvc\dataengine\extract\57\ff\{73CC533E-EC44-4B06-9938-59194BA2E3CD} into {73CC533E-EC44-4B06-9938-59194BA2E3CD}
2017-08-16 18:46:05.297 +0100 (Default,glen,nPx7erfpTgaavW6pI3GYrw,WZSE2wqWI2oAAEVAIeYAAAE-) catalina-exec-30 : INFO  com.tableausoftware.sos.TdfsProvider - finish injection extract/{73CC533E-EC44-4B06-9938-59194BA2E3CD}
2017-08-16 18:46:05.502 +0100 (Default,glen,nPx7erfpTgaavW6pI3GYrw,WZSE2wqWI2oAAEVAIeYAAAE-) catalina-exec-30 : INFO  com.tableausoftware.domain.content.publishing.WorkbookPublishingService - Retrieving project: siteId=1, id=null, name=Default
2017-08-16 18:46:05.665 +0100 (Default,glen,nPx7erfpTgaavW6pI3GYrw,WZSE2wqWI2oAAEVAIeYAAAE-) catalina-exec-30 : INFO  com.tableausoftware.domain.content.publishing.WorkbookPublishingService - No workbook entity exists, creating a new one.
 
So according to tableau an error 500 is because the header is missing or incorrect
http://onlinehelp.tableau.com/v9.0/api/rest_api/en-us/help.htm#REST/rest_api_concepts_publish.htm?Highlight=500
I will need to get back to you on getting my http request. But will try to for tomorrow

**Comment by adbertram** [comment]
I finally figured it out. I was using a PowerShell here string with new lines and the HTTP request needed to have carriage returns after each line.

Thank you for your help! I could have gotten as far as I had without your code.

**Comment by glenrobinson72** [comment]
Ok Great news that its working for you
All the best
Glen

**Comment by i02cagoa** [comment]
Hi Glen,
I'm getting the same error 500 trying to publish .tds datasources. Are you aware of this kind of error?

FYI: I have checked the vizportal-0.log and this what I am getting : "catalina-exec-1113 : ERROR com.tableausoftware.api.rest.util.RestApiControllerAdvice - Unhandled exception org.springframework.web.multipart.MultipartException: Could not parse multipart servlet request; nested exception is org.apache.commons.fileupload.FileUploadBase$IOFileUploadException: Processing of multipart/form-data request failed. Stream ended unexpectedly
org.springframework.web.multipart.MultipartException: Could not parse multipart servlet request; nested exception is org.apache.commons.fileupload.FileUploadBase$IOFileUploadException: Processing of multipart/form-data request failed. Stream ended unexpectedly"

Thanks in advance.

**Comment by glenrobinson72** [comment]
Hi Adam
What result do you get when you try to publish the same TDS using tabcmd?
Does this work ok
Glen

**Comment by i02cagoa** [comment]
I have been checking the Tableau Server Log, and I realized that the problem is because of Tableau Server can't access the TDE file which is pointed out by the TDS file.

There is any option to publish only the TDS file without the need to include the TDE file? I know that it is possible to export to TDSX and then publish the TDSX file, but that solution is not valid in my case.

Many thanks

**Comment by glenrobinson72** [comment]
Hi 
When you mean that the Server cant access the TDE, do you mean that the TDE is sitting in a different location (ie not on the Tableau Server)?

**Comment by i02cagoa** [comment]
Yes.
I will try to explain myself better. 
I want to create datasources and workbooks on my localmachine, commit changes to git (tds and twb files only), and then pubhlish the TDS to Tableau Server. But when I try to publish the TDS file Tableau Server raises an error because it cannot access the TDE file pointed out by the TDS file because, obiously, the TDE was not included in the Git Repository.

**Comment by glenrobinson72** [comment]
So, the TDE file you are pointing to, via the TDS...
Is that a file already generated (ie you are connecting to a TDE file),or is being generated via the TDS ( you are connecting to live data and then generating an extract)?

**Comment by i02cagoa** [comment]
The TDE file is been generated at same time that the TDS. That is the reason why the TDS point to the TDE. 

It is possible to connecto to live data and then convert the datasource from live to extract mode?

I think that is something not solved yet: https://community.tableau.com/ideas/2318.
That is my exactly purpose, create a continuous integration/delivery process.

Cheers.

**Comment by glenrobinson72** [comment]
When you connect to data, you have 2 options.. Have a live connection, or generate a TDE from the connection to that data. You can then generate a TDS from that connection
When you publish that data source to the server, if you have a live connection it is a TDS. if the data source is an extract, then it has to be a TDSX.
I dont think that there is any other option. You cant publish just the TDS for an extract and expect the server to generate the extract afterwards.. you need to publish the extract too
